//AUTH
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGOUT_USER = "LOGOUT_USER";

//DASHBOARD
export const GET_DASHBOARD_REQUEST = "GET_DASHBOARD_REQUEST";
export const GET_DASHBOARD_SUCCESS = "GET_DASHBOARD_SUCCESS";
export const GET_DASHBOARD_ERROR = "GET_DASHBOARD_ERROR";

//INVENTORY
export const GET_INVENTORY_SUMMARY_REPORT_REQUEST =
  "GET_INVENTORY_SUMMARY_REPORT_REQUEST";
export const GET_INVENTORY_SUMMARY_REPORT_SUCCESS =
  "GET_INVENTORY_SUMMARY_REPORT_SUCCESS";
export const GET_INVENTORY_SUMMARY_REPORT_ERROR =
  "GET_INVENTORY_SUMMARY_REPORT_ERROR";
export const CLEAR_INVENTORY_SUMMARY_REPORT_DATA =
  "CLEAR_INVENTORY_SUMMARY_REPORT_DATA";

// NEWS
export const GET_NEWS_REQUEST = "GET_NEWS_REQUEST";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_ERROR = "GET_MEETING_ERROR";
export const CREATE_NEWS_REQUEST = "CREATE_NEWS_REQUEST";
export const CREATE_NEWS_SUCCESS = "CREATE_NEWS_SUCCESS";
export const CREATE_NEWS_ERROR = "CREATE_NEWS_ERROR";
export const EDIT_NEWS_REQUEST = "EDIT_NEWS_REQUEST";
export const EDIT_NEWS_SUCCESS = "EDIT_NEWS_SUCCESS";
export const EDIT_NEWS_ERROR = "EDIT_NEWS_ERROR";
export const DELETE_NEWS_REQUEST = "DELETE_NEWS_REQUEST";
export const DELETE_NEWS_SUCCESS = "DELETE_NEWS_SUCCESS";
export const DELETE_NEWS_ERROR = "DELETE_NEWS_ERROR";

// MEETING
export const GET_MEETING_REQUEST = "GET_MEETING_REQUEST";
export const GET_MEETING_SUCCESS = "GET_MEETING_SUCCESS";
export const GET_MEETING_ERROR = "GET_MEETING_ERROR";
export const CREATE_MEETING_REQUEST = "CREATE_MEETING_REQUEST";
export const CREATE_MEETING_SUCCESS = "CREATE_MEETING_SUCCESS";
export const CREATE_MEETING_ERROR = "CREATE_MEETING_ERROR";
export const EDIT_MEETING_REQUEST = "EDIT_MEETING_REQUEST";
export const EDIT_MEETING_SUCCESS = "EDIT_MEETING_SUCCESS";
export const EDIT_MEETING_ERROR = "EDIT_MEETING_ERROR";
export const DELETE_MEETING_REQUEST = "DELETE_MEETING_REQUEST";
export const DELETE_MEETING_SUCCESS = "DELETE_MEETING_SUCCESS";
export const DELETE_MEETING_ERROR = "DELETE_MEETING_ERROR";
export const GET_MEETING_TYPE_REQUEST = "GET_MEETING_TYPE_REQUEST";
export const GET_MEETING_TYPE_SUCCESS = "GET_MEETING_TYPE_SUCCESS";
export const GET_MEETING_TYPE_ERROR = "GET_MEETING_TYPE_ERROR";

// NOTIFY
export const GET_NOTIFY_REQUEST = "GET_NOTIFY_REQUEST";
export const GET_NOTIFY_SUCCESS = "GET_NOTIFY_SUCCESS";
export const GET_NOTIFY_ERROR = "GET_NOTIFY_ERROR";
export const CREATE_NOTIFY_REQUEST = "CREATE_NOTIFY_REQUEST";
export const CREATE_NOTIFY_SUCCESS = "CREATE_NOTIFY_SUCCESS";
export const CREATE_NOTIFY_ERROR = "CREATE_NOTIFY_ERROR";
export const EDIT_NOTIFY_REQUEST = "EDIT_NOTIFY_REQUEST";
export const EDIT_NOTIFY_SUCCESS = "EDIT_NOTIFY_SUCCESS";
export const EDIT_NOTIFY_ERROR = "EDIT_NOTIFY_ERROR";
export const DELETE_NOTIFY_REQUEST = "DELETE_NOTIFY_REQUEST";
export const DELETE_NOTIFY_SUCCESS = "DELETE_NOTIFY_SUCCESS";
export const DELETE_NOTIFY_ERROR = "DELETE_NOTIFY_ERROR";
export const GET_NOTIFY_TYPE_REQUEST = "GET_NOTIFY_TYPE_REQUEST";
export const GET_NOTIFY_TYPE_SUCCESS = "GET_NOTIFY_TYPE_SUCCESS";
export const GET_NOTIFY_TYPE_ERROR = "GET_NOTIFY_TYPE_ERROR";
export const GET_NOTIFY_DOCUMEN_REFERENCES_REQUEST =
  "GET_NOTIFY_DOCUMEN_REFERENCES_REQUEST";
export const GET_DOCUMEN_REFERENCES_SUCCESS = "GET_DOCUMEN_REFERENCES_SUCCESS";
export const GET_DOCUMEN_REFERENCES_ERROR = "GET_DOCUMEN_REFERENCES_ERROR";

//APPEAL
export const GET_APPEAL_REQUEST = "GET_APPEAL_REQUEST";
export const GET_APPEAL_SUCCESS = "GET_APPEAL_SUCCESS";
export const GET_APPEAL_ERROR = "GET_APPEAL_ERROR";
export const CREATE_APPEAL_REQUEST = "CREATE_APPEAL_REQUEST";
export const CREATE_APPEAL_SUCCESS = "CREATE_APPEAL_SUCCESS";
export const CREATE_APPEAL_ERROR = "CREATE_APPEAL_ERROR";
export const EDIT_APPEAL_REQUEST = "EDIT_APPEAL_REQUEST";
export const EDIT_APPEAL_SUCCESS = "EDIT_APPEAL_SUCCESS";
export const EDIT_APPEAL_ERROR = "EDIT_APPEAL_ERROR";
export const DELETE_APPEAL_REQUEST = "DELETE_APPEAL_REQUEST";
export const DELETE_APPEAL_SUCCESS = "DELETE_APPEAL_SUCCESS";
export const DELETE_APPEAL_ERROR = "DELETE_APPEAL_ERROR";
export const GET_APPEAL_TYPE_REQUEST = "GET_APPEAL_TYPE_REQUEST";
export const GET_APPEAL_TYPE_SUCCESS = "GET_APPEAL_TYPE_SUCCESS";
export const GET_APPEAL_TYPE_ERROR = "GET_APPEAL_TYPE_ERROR";

//QUALIFIEDPERSON
export const GET_QUALIFIEDPERSON_REQUEST = "GET_QUALIFIEDPERSON_REQUEST";
export const GET_QUALIFIEDPERSON_SUCCESS = "GET_QUALIFIEDPERSON_SUCCESS";
export const GET_QUALIFIEDPERSON_ERROR = "GET_QUALIFIEDPERSON_ERROR";
export const CREATE_QUALIFIEDPERSON_REQUEST = "CREATE_QUALIFIEDPERSON_REQUEST";
export const CREATE_QUALIFIEDPERSON_SUCCESS = "CREATE_QUALIFIEDPERSON_SUCCESS";
export const CREATE_QUALIFIEDPERSON_ERROR = "CREATE_QUALIFIEDPERSON_ERROR";
export const EDIT_QUALIFIEDPERSON_REQUEST = "EDIT_QUALIFIEDPERSON_REQUEST";
export const EDIT_QUALIFIEDPERSON_SUCCESS = "EDIT_QUALIFIEDPERSON_SUCCESS";
export const EDIT_QUALIFIEDPERSON_ERROR = "EDIT_QUALIFIEDPERSON_ERROR";
export const DELETE_QUALIFIEDPERSON_REQUEST = "DELETE_QUALIFIEDPERSON_REQUEST";
export const DELETE_QUALIFIEDPERSON_SUCCESS = "DELETE_QUALIFIEDPERSON_SUCCESS";
export const DELETE_QUALIFIEDPERSON_ERROR = "DELETE_QUALIFIEDPERSON_ERROR";
export const GET_QUALIFIEDPERSON_TYPE_REQUEST =
  "GET_QUALIFIEDPERSON_TYPE_REQUEST";
export const GET_QUALIFIEDPERSON_TYPE_SUCCESS =
  "GET_QUALIFIEDPERSON_TYPE_SUCCESS";
export const GET_QUALIFIEDPERSON_TYPE_ERROR = "GET_QUALIFIEDPERSON_TYPE_ERROR";

//DEFENDANT
export const GET_DEFENDANT_REQUEST = "GET_DEFENDANT_REQUEST";
export const GET_DEFENDANT_SUCCESS = "GET_DEFENDANT_SUCCESS";
export const GET_DEFENDANT_ERROR = "GET_DEFENDANT_ERROR";
export const CREATE_DEFENDANT_REQUEST = "CREATE_DEFENDANT_REQUEST";
export const CREATE_DEFENDANT_SUCCESS = "CREATE_DEFENDANT_SUCCESS";
export const CREATE_DEFENDANT_ERROR = "CREATE_DEFENDANT_ERROR";
export const EDIT_DEFENDANT_REQUEST = "EDIT_DEFENDANT_REQUEST";
export const EDIT_DEFENDANT_SUCCESS = "EDIT_DEFENDANT_SUCCESS";
export const EDIT_DEFENDANT_ERROR = "EDIT_DEFENDANT_ERROR";
export const DELETE_DEFENDANT_REQUEST = "DELETE_DEFENDANT_REQUEST";
export const DELETE_DEFENDANT_SUCCESS = "DELETE_DEFENDANT_SUCCESS";
export const DELETE_DEFENDANT_ERROR = "DELETE_DEFENDANT_ERROR";
// LAW
export const GET_LAW_REQUEST = "GET_LAW_REQUEST";
export const GET_LAW_SUCCESS = "GET_LAW_SUCCESS";
export const GET_LAW_ERROR = "GET_LAW_ERROR";
export const CREATE_LAW_REQUEST = "CREATE_LAW_REQUEST";
export const CREATE_LAW_SUCCESS = "CREATE_LAW_SUCCESS";
export const CREATE_LAW_ERROR = "CREATE_LAW_ERROR";
export const EDIT_LAW_REQUEST = "EDIT_LAW_REQUEST";
export const EDIT_LAW_SUCCESS = "EDIT_LAW_SUCCESS";
export const EDIT_LAW_ERROR = "EDIT_LAW_ERROR";
export const DELETE_LAW_REQUEST = "DELETE_LAW_REQUEST";
export const DELETE_LAW_SUCCESS = "DELETE_LAW_SUCCESS";
export const DELETE_LAW_ERROR = "DELETE_LAW_ERROR";
export const GET_LAW_TYPE_REQUEST = "GET_LAW_TYPE_REQUEST";
export const GET_LAW_TYPE_SUCCESS = "GET_LAW_TYPE_SUCCESS";
export const GET_LAW_TYPE_ERROR = "GET_LAW_TYPE_ERROR";

// SETTING/BANNER
export const GET_BANNER_REQUEST = "GET_BANNER_REQUEST";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_ERROR = "GET_BANNER_ERROR";
export const CREATE_BANNER_REQUEST = "CREATE_BANNER_REQUEST";
export const CREATE_BANNER_SUCCESS = "CREATE_BANNER_SUCCESS";
export const CREATE_BANNER_ERROR = "CREATE_BANNER_ERROR";
export const EDIT_BANNER_REQUEST = "EDIT_BANNER_REQUEST";
export const EDIT_BANNER_SUCCESS = "EDIT_BANNER_SUCCESS";
export const EDIT_BANNER_ERROR = "EDIT_BANNER_ERROR";
export const DELETE_BANNER_REQUEST = "DELETE_BANNER_REQUEST";
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS";
export const DELETE_BANNER_ERROR = "DELETE_BANNER_ERROR";
export const CHANGE_STATUS_BANNER_REQUEST = "CHANGE_STATUS_BANNER_REQUEST";
export const CHANGE_STATUS_BANNER_SUCCESS = "CHANGE_STATUS_BANNER_SUCCESS";
export const CHANGE_STATUS_BANNER_ERROR = "CHANGE_STATUS_BANNER_ERROR";

// ADDRESS
export const GET_ADDRESS_REQUEST = "GET_ADDRESS_REQUEST";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_ERROR = "GET_ADDRESS_ERROR";
export const CREATE_ADDRESS_REQUEST = "CREATE_ADDRESS_REQUEST";
export const CREATE_ADDRESS_SUCCESS = "CREATE_ADDRESS_SUCCESS";
export const CREATE_ADDRESS_ERROR = "CREATE_ADDRESS_ERROR";
export const EDIT_ADDRESS_REQUEST = "EDIT_ADDRESS_REQUEST";
export const EDIT_ADDRESS_SUCCESS = "EDIT_ADDRESS_SUCCESS";
export const EDIT_ADDRESS_ERROR = "EDIT_ADDRESS_ERROR";

// PROPOSE
export const GET_PROPOSE_REQUEST = "GET_PROPOSE_REQUEST";
export const GET_PROPOSE_SUCCESS = "GET_PROPOSE_SUCCESS";
export const GET_PROPOSE_ERROR = "GET_PROPOSE_ERROR";
export const EDIT_PROPOSE_REQUEST = "EDIT_PROPOSE_REQUEST";
export const EDIT_PROPOSE_SUCCESS = "EDIT_PROPOSE_SUCCESS";
export const EDIT_PROPOSE_ERROR = "EDIT_PROPOSE_ERROR";

// ABOUTUS
export const GET_ABOUTUS_REQUEST = "GET_ABOUTUS_REQUEST";
export const GET_ABOUTUS_SUCCESS = "GET_ABOUTUS_SUCCESS";
export const GET_ABOUTUS_ERROR = "GET_ABOUTUS_ERROR";
export const EDIT_ABOUTUS_REQUEST = "EDIT_ABOUTUS_REQUEST";
export const EDIT_ABOUTUS_SUCCESS = "EDIT_ABOUTUS_SUCCESS";
export const EDIT_ABOUTUS_ERROR = "EDIT_ABOUTUS_ERROR";

// CONFIGURATION
export const GET_CONFIGURATION_REQUEST = "GET_CONFIGURATION_REQUEST";
export const GET_CONFIGURATION_SUCCESS = "GET_CONFIGURATION_SUCCESS";
export const GET_CONFIGURATION_ERROR = "GET_CONFIGURATION_ERROR";
export const EDIT_CONFIGURATION_REQUEST = "EDIT_CONFIGURATION_REQUEST";
export const EDIT_CONFIGURATION_SUCCESS = "EDIT_CONFIGURATION_SUCCESS";
export const EDIT_CONFIGURATION_ERROR = "EDIT_CONFIGURATION_ERROR";

// PUBLICFILE
export const GET_PUBLICFILE_REQUEST = "GET_PUBLICFILE_REQUEST";
export const GET_PUBLICFILE_SUCCESS = "GET_PUBLICFILE_SUCCESS";
export const GET_PUBLICFILE_ERROR = "GET_PUBLICFILE_ERROR";
export const EDIT_PUBLICFILE_REQUEST = "EDIT_PUBLICFILE_REQUEST";
export const EDIT_PUBLICFILE_SUCCESS = "EDIT_PUBLICFILE_SUCCESS";
export const EDIT_PUBLICFILE_ERROR = "EDIT_PUBLICFILE_ERROR";

// OFFICEOFQUALIFICATION
export const GET_OFFICEOFQUALIFICATION_REQUEST =
  "GET_OFFICEOFQUALIFICATION_REQUEST";
export const GET_OFFICEOFQUALIFICATION_SUCCESS =
  "GET_OFFICEOFQUALIFICATION_SUCCESS";
export const GET_OFFICEOFQUALIFICATION_ERROR =
  "GET_OFFICEOFQUALIFICATION_ERROR";
export const EDIT_OFFICEOFQUALIFICATION_REQUEST =
  "EDIT_OFFICEOFQUALIFICATION_REQUEST";
export const EDIT_OFFICEOFQUALIFICATION_SUCCESS =
  "EDIT_OFFICEOFQUALIFICATION_SUCCESS";
export const EDIT_OFFICEOFQUALIFICATION_ERROR =
  "EDIT_OFFICEOFQUALIFICATION_ERROR";

// HISTORY
export const GET_HISTORY_REQUEST = "GET_HISTORY_REQUEST";
export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS";
export const GET_HISTORY_ERROR = "GET_HISTORY_ERROR";
export const CREATE_HISTORY_REQUEST = "CREATE_HISTORY_REQUEST";
export const CREATE_HISTORY_SUCCESS = "CREATE_HISTORY_SUCCESS";
export const CREATE_HISTORY_ERROR = "CREATE_HISTORY_ERROR";
export const EDIT_HISTORY_REQUEST = "EDIT_HISTORY_REQUEST";
export const EDIT_HISTORY_SUCCESS = "EDIT_HISTORY_SUCCESS";
export const EDIT_HISTORY_ERROR = "EDIT_HISTORY_ERROR";
export const DELETE_HISTORY_REQUEST = "DELETE_HISTORY_REQUEST";
export const DELETE_HISTORY_SUCCESS = "DELETE_HISTORY_SUCCESS";
export const DELETE_HISTORY_ERROR = "DELETE_HISTORY_ERROR";

//RESETPASSWORDME
export const RESET_PASSWORD_ME_REQUEST = "RESET_PASSWORD_ME_REQUEST";
export const RESET_PASSWORD_ME_SUCCESS = "RESET_PASSWORD_ME_SUCCESS";
export const RESET_PASSWORD_ME_ERROR = "RESET_PASSWORD_ME_ERROR";

//LOG
export const GET_API_LOG_REQUEST = "GET_API_LOG_REQUEST";
export const GET_API_LOG_SUCCESS = "GET_API_LOG_SUCCESS";
export const GET_API_LOG_ERROR = "GET_API_LOG_ERROR";
export const CLEAR_API_LOG_DATA = "CLEAR_API_LOG_DATA";

//USER
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";
export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_ERROR = "EDIT_USER_ERROR";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";
export const RESET_PASSWORD_USER_REQUEST = "RESET_PASSWORD_USER_REQUEST";
export const RESET_PASSWORD_USER_SUCCESS = "RESET_PASSWORD_USER_SUCCESS";
export const RESET_PASSWORD_USER_ERROR = "RESET_PASSWORD_USER_ERROR";

//ROLE
export const GET_ROLES_REQUEST = "GET_ROLES_REQUEST";
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_ROLES_ERROR = "GET_ROLES_ERROR";
export const CREATE_ROLE_REQUEST = "CREATE_ROLE_REQUEST";
export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const CREATE_ROLE_ERROR = "CREATE_ROLE_ERROR";
export const EDIT_ROLE_REQUEST = "EDIT_ROLE_REQUEST";
export const EDIT_ROLE_SUCCESS = "EDIT_ROLE_SUCCESS";
export const EDIT_ROLE_ERROR = "EDIT_ROLE_ERROR";

//CHAGNE PASSWORD
export const CHANGE_PASSWORD_ME_REQUEST = "CHANGE_PASSWORD_ME_REQUEST";
export const CHANGE_PASSWORD_ME_SUCCESS = "CHANGE_PASSWORD_ME_SUCCESS";
export const CHANGE_PASSWORD_ME_ERROR = "CHANGE_PASSWORD_ME_ERROR";

//LOADING
export const SHOW_LOADING = "SHOW_LOADING";
export const SHOW_LOADING_SMALL = "SHOW_LOADING_SMALL";
export const HIDE_LOADING = "HIDE_LOADING";
export const HIDE_LOADING_SMALL = "HIDE_LOADING_SMALL";

//STORAGE
export const FETCH_STORAGE_REQUEST = "FETCH_STORAGE_REQUEST";
export const FETCH_STORAGE_SUCCESS = "FETCH_STORAGE_SUCCESS";
export const FETCH_STORAGE_ERROR = "FETCH_STORAGE_ERROR";
export const PROJECT_KEY = "ONEP";

//CHANGESTATUS
export const CHANGE_STATUS_REQUEST = "CHANGE_STATUS_REQUEST";
export const CHANGE_STATUS_SUCCESS = "CHANGE_STATUS_SUCCESS";
export const CHANGE_STATUS_ERROR = "CHANGE_STATUS_ERROR";

// - MODAL - //
export const HIDE_MODAL = "HIDE_MODAL";

//USER

export const OPEN_RESET_PASSWORD_MODAL = "OPEN_RESET_PASSWORD_MODAL";

//ROLE
export const OPEN_VIEW_ROLE_MODAL = "OPEN_VIEW_ROLE_MODAL";
export const OPEN_CREATE_ROLE_MODAL = "OPEN_CREATE_ROLE_MODAL";
export const OPEN_EDIT_ROLE_MODAL = "OPEN_EDIT_ROLE_MODAL";

//NEWS
export const OPEN_DETAIL_NEWS_MODAL = "OPEN_DETAIL_NEWS_MODAL";
export const OPEN_CREATE_NEWS_MODAL = "OPEN_CREATE_NEWS_MODAL";
export const OPEN_EDIT_NEWS_MODAL = "OPEN_EDIT_NEWS_MODAL";

//MEETING
export const OPEN_DETAIL_MEETING_MODAL = "OPEN_DETAIL_MEETING_MODAL";
export const OPEN_CREATE_MEETING_MODAL = "OPEN_CREATE_MEETING_MODAL";
export const OPEN_EDIT_MEETING_MODAL = "OPEN_EDIT_MEETING_MODAL";

//NOTIFY
export const OPEN_DETAIL_NOTIFY_MODAL = "OPEN_DETAIL_NOTIFY_MODAL";
export const OPEN_CREATE_NOTIFY_MODAL = "OPEN_CREATE_NOTIFY_MODAL";
export const OPEN_EDIT_NOTIFY_MODAL = "OPEN_EDIT_NOTIFY_MODAL";

//QUALIFIEDPERSON
export const OPEN_DETAIL_QUALIFIEDPERSON_MODAL =
  "OPEN_DETAIL_QUALIFIEDPERSON_MODAL";
export const OPEN_CREATE_QUALIFIEDPERSON_MODAL =
  "OPEN_CREATE_QUALIFIEDPERSON_MODAL";
export const OPEN_EDIT_QUALIFIEDPERSON_MODAL =
  "OPEN_EDIT_QUALIFIEDPERSON_MODAL";

//DEFENDANT
export const OPEN_DETAIL_DEFENDANT_MODAL = "OPEN_DETAIL_DEFENDANT_MODAL";
export const OPEN_CREATE_DEFENDANT_MODAL = "OPEN_CREATE_DEFENDANT_MODAL";
export const OPEN_EDIT_DEFENDANT_MODAL = "OPEN_EDIT_DEFENDANT_MODAL";

//APPEAL
export const OPEN_DETAIL_APPEAL_MODAL = "OPEN_DETAIL_APPEAL_MODAL";
export const OPEN_CREATE_APPEAL_MODAL = "OPEN_CREATE_APPEAL_MODAL";
export const OPEN_EDIT_APPEAL_MODAL = "OPEN_EDIT_APPEAL_MODAL";

//LAW
export const OPEN_DETAIL_LAW_MODAL = "OPEN_DETAIL_LAW_MODAL";
export const OPEN_CREATE_LAW_MODAL = "OPEN_CREATE_LAW_MODAL";
export const OPEN_EDIT_LAW_MODAL = "OPEN_EDIT_LAW_MODAL";

//HISTORY
export const OPEN_HISTORY_DETAIL_MODAL = "OPEN_HISTORY_DETAIL_MODAL";
export const OPEN_CREATE_HISTORY_MODAL = "OPEN_CREATE_HISTORY_MODAL";
export const OPEN_EDIT_HISTORY_MODAL = "OPEN_EDIT_HISTORY_MODAL";

//USER
export const OPEN_DETAIL_USER_MODAL = "OPEN_DETAIL_USER_MODAL";
export const OPEN_CREATE_USER_MODAL = "OPEN_CREATE_USER_MODAL";
export const OPEN_EDIT_USER_MODAL = "OPEN_EDIT_USER_MODAL";

//SETTING/BANNER
export const OPEN_DETAIL_BANNER_MODAL = "OPEN_DETAIL_BANNER_MODAL";
export const OPEN_CREATE_BANNER_MODAL = "OPEN_CREATE_BANNER_MODAL";
export const OPEN_EDIT_BANNER_MODAL = "OPEN_EDIT_BANNER_MODAL";
